### ISSUE TITLE
Garden Stone no recipe

### ISSUE THREAD

**Issue by WookieWarlordNZ** [RipDatPow/skyplebbin#1]
Hi,

I am stuck on Chapter 2 with the Garden stone. There is no recipe for it, and the book only makes mention that it can be found in the void world soil. I couldn't find a recipe for this. Any tips or is this a bug?

**Comment by RipDatPow** [comment]
Hi WookieWarlordNZ! There is a hint in the SkyPlebbin Guide Book about garden stones. You can acquire them through harvesting crops including beetroots, cabbage, melon, pumpkin, tomatoes, and wheat. You should have received a seed sack as a quest reward, be sure to claim it in FTB quests so you can farm these crops! Good luck!

**Comment by WookieWarlordNZ** [comment]
Ah brilliant! Thank you :)
