### ISSUE TITLE
Water for crops

### ISSUE THREAD

**Issue by Rioran** [RipDatPow/skyplebbin#2]
Hi there!

I got stuck on chapter 2. Can't find out how to get water for crops to grow. I red both books several times with no result. As I see it - crops are essentual to get through the chapter.

**Comment by RipDatPow** [comment]
Hi Rioran! To grow crops and trees, simply hit the shift key repetitively (squat) when near your crops and they will grow very quickly. SkyPlebbin uses the 'SquatGrow' mod which provides the squat-to-grow functionality common in skyblock style modpacks. Hope this help! Good luck and hope you enjoy the rest of the modpack :)
